# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: create virtualenv
          command: |
            cd project-ml-microservice-kubernetes
            make setup
            
      - run:
          name: install dependencies
          command: |
            cd project-ml-microservice-kubernetes
            . .devops/bin/activate
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lints!
      - setup_remote_docker
      - run:
          name: run lint
          command: |
            cd project-ml-microservice-kubernetes
            . .devops/bin/activate
            make lint